# Generated by Django 5.0.4 on 2026-04-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                ],
                default="cash_on_delivery",
                max_length=50,
            ),
        ),
    ]
